version: '3.8'
services:
  streamlit-app:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - TZ=Europe/Moscow
    command: [ "streamlit", "run", "streamlit_app.py", "--server.port=8501" ]

  jupyterlab:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - .:/app
    environment:
      - TZ=Europe/Moscow
    command: ["jupyter", "lab", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root", "--NotebookApp.token=''"]
